"""Run the research pipeline end-to-end and export a findings JSON.

This is the artifact a human reviewer reads to decide whether a method
demonstrated here is worth reimplementing in the production TypeScript
analytics engine. It always includes: honest metrics, baseline comparisons
and lift, sample sizes, class balance, bootstrap confidence intervals,
feature importances, and an explicit data provenance statement.

Usage:
    python scripts/export_findings.py \
        [--events-csv data/sample_logs.csv] \
        [--spike-threshold 200.0] [--lookback-hours 6.0] \
        [--train-frac 0.6] [--val-frac 0.2] \
        [--data-provenance "..."] [--output outputs/findings.json]
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from src.config import PATHS
from src.features import FeatureConfig, build_training_examples, to_dataframe
from src.modeling import SplitConfig, train_and_evaluate

EVENT_COLUMNS: list[str] = [
    "timestamp",
    "event_type",
    "carbs_g",
    "med_name",
    "med_units",
    "glucose_mgdl",
    "notes",
]

# Any events source whose filename contains one of these substrings is
# treated as synthetic unless the caller explicitly overrides
# --data-provenance. This is a conservative heuristic, not a guarantee --
# always pass --data-provenance explicitly for real data.
SYNTHETIC_FILENAME_MARKERS: tuple[str, ...] = ("sample", "synthetic", "generated", "fixture")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--events-csv",
        type=Path,
        default=PATHS.DATA / "sample_logs.csv",
        help="CSV of raw events (timestamp, event_type, carbs_g, med_name, med_units, glucose_mgdl, notes).",
    )
    parser.add_argument("--spike-threshold", type=float, default=200.0, dest="spike_threshold_mgdl")
    parser.add_argument("--lookback-hours", type=float, default=6.0)
    parser.add_argument("--train-frac", type=float, default=0.6)
    parser.add_argument("--val-frac", type=float, default=0.2)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument("--n-estimators", type=int, default=300)
    parser.add_argument("--cv-splits", type=int, default=5)
    parser.add_argument(
        "--data-provenance",
        type=str,
        default=None,
        help="Explicit statement of where the data came from. Overrides the filename-based heuristic.",
    )
    parser.add_argument("--output", type=Path, default=None, help="Output JSON path (default: outputs/findings_<ts>.json)")
    return parser.parse_args()


def infer_data_provenance(events_csv: Path, override: str | None) -> str:
    if override:
        return override
    name = events_csv.name.lower()
    if any(marker in name for marker in SYNTHETIC_FILENAME_MARKERS):
        return (
            f"SYNTHETIC sample data (source file: {events_csv.name}) -- generated by a script, "
            "not from real device/patient data. Results below carry NO CLINICAL VALIDITY and must "
            "not be used to make claims about real-world model performance."
        )
    return (
        f"UNVERIFIED provenance (source file: {events_csv.name}). No --data-provenance was given and "
        "the filename does not match known synthetic-data markers; this does NOT confirm the data is "
        "real or clinically valid -- verify the source before trusting these metrics."
    )


def load_events_dataframe(events_csv: Path) -> pd.DataFrame:
    if not events_csv.exists():
        raise FileNotFoundError(
            f"Events CSV not found: {events_csv}. Generate one with "
            "examples/generate_sample_data.py + scripts/ingest_csv.py, or pass --events-csv."
        )
    raw = pd.read_csv(events_csv)
    for col in EVENT_COLUMNS:
        if col not in raw.columns:
            raw[col] = None
    rows = [tuple(r[col] for col in EVENT_COLUMNS) for _, r in raw.iterrows()]
    return to_dataframe(rows)


def extract_feature_importances(report) -> dict[str, float]:
    """Map the trained RandomForest's feature_importances_ back to preprocessed feature names."""
    pipe = report.model
    pre = pipe.named_steps["preprocess"]
    clf = pipe.named_steps["clf"]
    try:
        names = list(pre.get_feature_names_out())
    except Exception:
        names = [f"feature_{i}" for i in range(len(clf.feature_importances_))]
    importances = clf.feature_importances_.tolist()
    pairs = sorted(zip(names, importances), key=lambda p: p[1], reverse=True)
    return {name: float(value) for name, value in pairs}


def main() -> None:
    args = parse_args()

    events_df = load_events_dataframe(args.events_csv)
    feature_config = FeatureConfig(
        spike_threshold_mgdl=args.spike_threshold_mgdl, lookback_hours=args.lookback_hours
    )
    examples_df = build_training_examples(events_df, config=feature_config)

    data_provenance = infer_data_provenance(args.events_csv, args.data_provenance)

    split_config = SplitConfig(train_frac=args.train_frac, val_frac=args.val_frac)
    report = train_and_evaluate(
        examples_df,
        data_provenance=data_provenance,
        feature_config=feature_config,
        split_config=split_config,
        random_state=args.random_state,
        n_estimators=args.n_estimators,
        cv_splits=args.cv_splits,
    )

    findings = report.to_dict()
    findings["generated_at_utc"] = datetime.now(timezone.utc).isoformat()
    findings["events_source"] = str(args.events_csv)
    findings["n_raw_events"] = int(len(events_df))
    findings["n_training_examples"] = int(len(examples_df))
    findings["feature_importances"] = extract_feature_importances(report)
    findings["notes"] = (
        "Evaluated with a chronological train/val/test split (earliest -> latest); "
        "cross-validation for robustness uses sklearn TimeSeriesSplit. Every model metric "
        "is reported alongside majority-class, prevalence, and previous-reading baselines "
        "with the model's lift over each. See docs/ML_PIPELINE.md for full methodology."
    )

    PATHS.OUTPUTS.mkdir(parents=True, exist_ok=True)
    if args.output is not None:
        output_path = args.output
    else:
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        output_path = PATHS.OUTPUTS / f"findings_{ts}.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(findings, f, indent=2, default=lambda o: float(o) if isinstance(o, np.floating) else str(o))

    print(f"Data provenance: {data_provenance}")
    print(f"Sample sizes: {report.sample_sizes}")
    print(f"Class balance (positive rate): {report.class_balance}")
    print("Model metrics (test):", report.model_metrics)
    print("Baseline metrics (test):", report.baseline_metrics)
    print("Lift over baselines:", report.lift_over_baselines)
    if report.warnings:
        print("Warnings:")
        for w in report.warnings:
            print(f"  - {w}")
    print(f"Wrote findings report: {output_path}")


if __name__ == "__main__":
    main()
