/** IANA zones offered in Settings: every Canadian zone, plus common others. */
export const TIMEZONE_OPTIONS: { value: string; label: string }[] = [
  // Canada
  { value: 'America/St_Johns', label: 'Newfoundland Time (St. John’s)' },
  { value: 'America/Halifax', label: 'Atlantic Time (Halifax)' },
  { value: 'America/Moncton', label: 'Atlantic Time (Moncton)' },
  { value: 'America/Glace_Bay', label: 'Atlantic Time (Glace Bay)' },
  { value: 'America/Goose_Bay', label: 'Atlantic Time (Goose Bay)' },
  { value: 'America/Blanc-Sablon', label: 'Atlantic Time, no DST (Blanc-Sablon)' },
  { value: 'America/Toronto', label: 'Eastern Time (Toronto)' },
  { value: 'America/Montreal', label: 'Eastern Time (Montreal)' },
  { value: 'America/Iqaluit', label: 'Eastern Time (Iqaluit)' },
  { value: 'America/Nipigon', label: 'Eastern Time (Nipigon)' },
  { value: 'America/Thunder_Bay', label: 'Eastern Time (Thunder Bay)' },
  { value: 'America/Winnipeg', label: 'Central Time (Winnipeg)' },
  { value: 'America/Resolute', label: 'Central Time (Resolute)' },
  { value: 'America/Rainy_River', label: 'Central Time (Rainy River)' },
  { value: 'America/Regina', label: 'Central Time, no DST (Regina)' },
  { value: 'America/Swift_Current', label: 'Central Time, no DST (Swift Current)' },
  { value: 'America/Edmonton', label: 'Mountain Time (Edmonton)' },
  { value: 'America/Cambridge_Bay', label: 'Mountain Time (Cambridge Bay)' },
  { value: 'America/Yellowknife', label: 'Mountain Time (Yellowknife)' },
  { value: 'America/Inuvik', label: 'Mountain Time (Inuvik)' },
  { value: 'America/Creston', label: 'Mountain Time, no DST (Creston)' },
  { value: 'America/Dawson_Creek', label: 'Mountain Time, no DST (Dawson Creek)' },
  { value: 'America/Fort_Nelson', label: 'Mountain Time, no DST (Fort Nelson)' },
  { value: 'America/Vancouver', label: 'Pacific Time (Vancouver)' },
  { value: 'America/Whitehorse', label: 'Pacific Time (Whitehorse)' },
  { value: 'America/Dawson', label: 'Pacific Time (Dawson)' },
  // United States
  { value: 'America/New_York', label: 'Eastern Time (New York)' },
  { value: 'America/Chicago', label: 'Central Time (Chicago)' },
  { value: 'America/Denver', label: 'Mountain Time (Denver)' },
  { value: 'America/Phoenix', label: 'Mountain Time, no DST (Phoenix)' },
  { value: 'America/Los_Angeles', label: 'Pacific Time (Los Angeles)' },
  { value: 'America/Anchorage', label: 'Alaska Time (Anchorage)' },
  { value: 'Pacific/Honolulu', label: 'Hawaii Time (Honolulu)' },
  // Other common international zones
  { value: 'UTC', label: 'Coordinated Universal Time (UTC)' },
  { value: 'America/Mexico_City', label: 'Mexico City' },
  { value: 'America/Sao_Paulo', label: 'São Paulo' },
  { value: 'Europe/London', label: 'London' },
  { value: 'Europe/Dublin', label: 'Dublin' },
  { value: 'Europe/Paris', label: 'Paris' },
  { value: 'Europe/Berlin', label: 'Berlin' },
  { value: 'Europe/Madrid', label: 'Madrid' },
  { value: 'Europe/Rome', label: 'Rome' },
  { value: 'Europe/Athens', label: 'Athens' },
  { value: 'Europe/Moscow', label: 'Moscow' },
  { value: 'Africa/Cairo', label: 'Cairo' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg' },
  { value: 'Asia/Jerusalem', label: 'Jerusalem' },
  { value: 'Asia/Dubai', label: 'Dubai' },
  { value: 'Asia/Kolkata', label: 'Mumbai / Delhi (Kolkata)' },
  { value: 'Asia/Karachi', label: 'Karachi' },
  { value: 'Asia/Dhaka', label: 'Dhaka' },
  { value: 'Asia/Bangkok', label: 'Bangkok' },
  { value: 'Asia/Singapore', label: 'Singapore' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong' },
  { value: 'Asia/Shanghai', label: 'Shanghai' },
  { value: 'Asia/Tokyo', label: 'Tokyo' },
  { value: 'Asia/Seoul', label: 'Seoul' },
  { value: 'Australia/Perth', label: 'Perth' },
  { value: 'Australia/Adelaide', label: 'Adelaide' },
  { value: 'Australia/Sydney', label: 'Sydney' },
  { value: 'Pacific/Auckland', label: 'Auckland' },
];
