import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          // `const { drop: _drop, ...rest } = obj` is the idiomatic way to omit
          // a key; the discarded binding is deliberately unused.
          ignoreRestSiblings: true,
        },
      ],
    },
  },
  {
    // Playwright's locator.count() is one of the few APIs that does NOT
    // auto-wait — it reports whatever is in the DOM at that instant. Several
    // app pages stream behind a loading.tsx boundary, so page.goto() resolves
    // on the skeleton and an immediate count() reads 0. That produced a CI-only
    // flake that passed locally roughly half the time.
    //
    // Counts must go through tests/e2e/records.ts, which waits for the list or
    // the empty state to render first.
    files: ['tests/e2e/**/*.spec.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "CallExpression[callee.property.name='count']",
          message:
            'locator.count() does not auto-wait and reads 0 on streamed pages. Use countRecordRows() from tests/e2e/records.ts, or await an expect(...).toBeVisible() / toHaveCount() first.',
        },
      ],
    },
  },
  // next-env.d.ts is generated by Next.js on every build and must keep its
  // triple-slash references.
  { ignores: ['.next/**', 'node_modules/**', 'ml/**', 'public/sw.js', 'next-env.d.ts'] },
];

export default config;
